chore(release):  bump version
projectcaluma/caluma-interval pull request #370
Opened 2022-12-09 09:12 UTC by StephanH90

2022-12-09 10:02 UTC, open-dynaMIX requested changes
Why is this a major version bump? Should be `2.0.1`, right?

2022-12-09 10:15 UTC, StephanH90 commented
We are using the "newer" filter syntax. I mean its pretty far fetched since nobody is using such an old caluma version anyway (I hope?)








--

Adfinis AG
Stephan Hug, Software Engineer, GPG Key: C831A3A24D5719BA619604E622CD5AB4CFECD397
Giessereiweg 5 | CH-3007 Berne
Office +41 31 550 31 11 | Direct +41 31 550 31 02
www.adfinis.com










-----Original message-----
From: Fabio ***@***.***>
Sent: Friday 9th December 2022 11:03
To: projectcaluma/caluma-interval ***@***.***>
Cc: Stephan Hug ***@***.***>; Author ***@***.***>
Subject: Re: [projectcaluma/caluma-interval] chore(release): bump version (PR #370)

@open-dynaMIX requested changes on this pull request.

Why is this a major version bump? Should be 2.0.1, right?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-12-09 10:20 UTC, open-dynaMIX commented
Ah, I see. Then it would be good to add this info to the changelog.

2022-12-09 12:01 UTC, StephanH90 commented
I wanted to, but I was looking at the changelog of caluma and I couldn't find when it was changed. I went as far back as v5. So I wasn't sure if it was worth the effort to dig further.



Perhaps we can just write something like: "requires Caluma > v5" or similar.








--

Adfinis AG
Stephan Hug, Software Engineer, GPG Key: C831A3A24D5719BA619604E622CD5AB4CFECD397
Giessereiweg 5 | CH-3007 Berne
Office +41 31 550 31 11 | Direct +41 31 550 31 02
www.adfinis.com










-----Original message-----
From: Fabio ***@***.***>
Sent: Friday 9th December 2022 11:20
To: projectcaluma/caluma-interval ***@***.***>
Cc: Stephan Hug ***@***.***>; Author ***@***.***>
Subject: Re: [projectcaluma/caluma-interval] chore(release): bump version (PR #370)

Ah, I see. Then it would be good to add this info to the changelog.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-09 09:47 UTC, open-dynaMIX commented
I just dug through the commit history of caluma. The new-style filter-syntax has been introduced with [this PR](https://github.com/projectcaluma/caluma/pull/708), merged on Oct 10, 2019. The first release with this changes must therefore be  [v3.0.0](https://github.com/projectcaluma/caluma/releases/tag/v3.0.0). This somehow didn't make it into the release notes, tho...

2023-01-27 09:05 UTC, open-dynaMIX approved these changes
One last nitpick, sorry! :see_no_evil:

2023-01-27 09:05 UTC, open-dynaMIX commented on CHANGELOG.md
> +* Due to the usage of the newer style filter syntax for queries (6e63070064e2f72ae3226a919bbecf876e31d26f) Caluma V5 or newer is required
```suggestion
* Due to the usage of the newer style filter syntax for queries (6e63070064e2f72ae3226a919bbecf876e31d26f) Caluma V3 or newer is required
```

2023-01-30 09:03 UTC, StephanH90 commented on CHANGELOG.md
> +* Due to the usage of the newer style filter syntax for queries (6e63070064e2f72ae3226a919bbecf876e31d26f) Caluma V5 or newer is required
Done. Pls check and resolve thx. :100:

2023-01-30 09:27 UTC, merged